name: Mi Primer Pipeline DevOps

on:
  push:
    branches: ["main"]

# 1. Le decimos a la infraestructura de GitHub que use Node 24 internamente
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  construir-y-desplegar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Traer el código al contenedor
        uses: actions/checkout@v4
        
      - name: Instalar entorno de ejecución
        uses: actions/setup-node@v4
        with:
          # 2. Actualizamos esto a 22 para igualar tu entorno local
          node-version: 22
          
      - name: Instalar dependencias y compilar
        run: |
          npm install
          npm run build

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist